apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akosha-rolebinding
  namespace: akosha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akosha-role
subjects:
- kind: ServiceAccount
  name: akosha-sa
  namespace: akosha
